spring:
  datasource:
    url: jdbc:opengauss://139.9.131.107:26000/mydb
    username: zeyu
    password: '102301237lzy.'
    driver-class-name: org.opengauss.Driver
  jackson:
    default-property-inclusion: non_null
  data:
    redis:
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
      port: 6379
      host: 106.15.90.163
      database: 0
      timeout: 10000
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=300s
  threads:
    virtual:
      enabled: true # tomcat启用虚拟线程


mybatis:
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.zeyuli.pojo
  mapper-locations: classpath:/mappers/*.xml

jwt:
  token:
    tokenExpiration: 24
    tokenSignKey: 4Pe5KKKoVYj8nJw7MHQ2PpIPjdc5vhIaJUge38cMkc9be3CLIl4vxt2cYLzxBMFDdWEgWj8d9B4BYr73DqWP0g==

cache:
  baseKey:
    billList: "bill:list:"
  redis:
    # 基础过期时间(分钟)
    expireTime: 30
    # 空值缓存时间(秒)
    nullCacheTime: 15
    baseKey:
      # 管理员的key后缀
      admin:
        login: "admin:token:"
      # 用户的key后缀
      user:
        login: "user:token:"
    nullData : "EMPTY"